name: nbody
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  
  - ipykernel
  - ipympl
  - matplotlib
  - pandas
  - plotly
  - seaborn
  
  - debugpy
  - pytest

  - numpy
  - cupy
  - numba
  - numba-cuda  

  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1 

  - pip
  
  # --- Install PyKeOps via pip ---
  - pip:
      - pykeops